// import {StyleSheet} from 'react-native';
import {StyleSheet, StatusBar, Dimensions} from 'react-native';
// import {grey100} from 'react-native-paper/lib/typescript/styles/colors';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    // alignSelf: "center",
    // backgroundColor: "#f5fcff"
  },
  fab: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    margin: 16,
  },
  back: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    marginTop: 16,
    width: 80,
    height: 80,
    paddingTop: 25,
    backgroundColor: '#a60',
    borderRadius: 50,
    alignItems: 'center',
    // backgroundColor: '#e1e1e1'
  },
  addtostack: {
    position: 'absolute',
    width: 70,
    height: 40,
    left: 0,
    bottom: 0,
    margin: 16,
    padding: 10,
    backgroundColor: '#75714d',
    borderRadius: 20,
    alignItems: 'center',
  },

  avatar: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
    // left:-100,
    // top: 100,
  },
  abs_mark: {
    height: 100,
    alignSelf: 'center',
    position: 'relative',
    left: 0,
    top: 0,
  },
  mathcontainer: {
    overflow: 'hidden',
    flex: 1,
    // borderColor: '#000',
    // color:'#c92094',
    // borderRadius: '10px',
    fontWeight: 'bold',
    // borderWidth: 0.1,
    alignSelf: 'center',
    // backgroundColor:'#75714d',
    // opacity: 0.1,
    width: 250,
    // height:60,
    position: 'relative',
    // left:     80,
    top: 0,
    // alignSelf: "center",
  },
  heading: {
    color: '#FFCB1F',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    margin: 5,
    padding: 2,
    fontSize: 20,
    color: '#FC766AFF',
    shadowRadius: 3,
    borderRadius: 20,
    borderColor: '#ADEFD1FF',
    borderWidth: 1,
    backgroundColor: '#101820FF',
  },
  prob_score: {
    color: '#FFCB1F',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    margin: 5,
    padding: 2,
    fontSize: 25,
    color: '#f00',
    shadowRadius: 3,
    borderRadius: 5,
    borderColor: '#FDE0D1FF',
    borderWidth: 1,
    backgroundColor: '#101820FF',
  },
  line: {
    borderBottomColor: 'black',
    borderBottomWidth: 4,
    marginBottom: 10,
  },
  line50: {
    justifyContent: 'center',
    alignSelf: 'center',
    borderBottomColor: '#ddd',
    borderBottomWidth: 4,
    marginTop: 10,
    marginBottom: 0,
    // marginLeft:100,
    width: 200,
  },
  intro: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  num: {
    // margin: 5,
    // marginTop:10,
    height: 70,
    width: windowWidth / 10,
    textAlign: 'center',
    fontSize: 50,
    color: '#47d16d',
    fontWeight: 'bold',
  },
  lendnumbers: {
    height: 30,
    width: windowWidth / 10,
    fontSize: 20,
    color: '#47d16d',
    fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
    marginTop: 5,
    backgroundColor: '#2221',
    // borderColor: '#8d3ec2',
    // borderWidth: 1,
    borderRadius: 10,
    padding: 5,
  },
  sign: {
    margin: 5,
    height: 80,
    width: 50,
    textAlign: 'center',
    fontSize: 60,
    // borderColor: '#FFCB1F',
    color: '#c92094',
    // borderRadius: '10px',
    fontWeight: 'bold',
    // borderWidth: 1
  },

  abs_sign: {
    color: '#c92094',
    // borderRadius: '10px',
    fontWeight: 'bold',
    // backgroundColor: '#FFFFFF',
    height: 50,
    fontSize: 50,
    alignSelf: 'center',
    // flexDirection: 'row',
    // bottom: 0,
    // justifyContent: 'space-between',
    position: 'relative',
    left: -80,
    top: 125,
  },

  input: {
    height: 70,
    textAlign: 'center',
    alignSelf: 'center',
    width: windowWidth / 10,
    fontSize: 50,
    marginTop: 5,
    borderColor: '#8d3ec2',
    borderWidth: 1,
    borderRadius: 10,
    padding: 5,
    // marginTop: 24,
    // marginBottom: 24,
    color: '#FFCB1F',
  },
  name: {
    height: 70,
    textAlign: 'center',
    alignSelf: 'center',
    width: 250,
    fontSize: 30,
    margin: 5,
    borderColor: '#8d3ec2',
    borderWidth: 1,
    borderRadius: 10,
    // marginTop: 24,
    // marginBottom: 24,
    color: '#FFCB1F',
  },
  btn: {
    backgroundColor: '#1D1D1B',
  },
  buttonText: {
    alignSelf: 'center',
    padding: 30,
    fontSize: 25,
    color: '#FFCB1F',
    fontWeight: 'bold',
  },
  result: {
    alignSelf: 'center',
    color: '#FFCB1F',
    fontSize: 65,
    padding: 15,
  },
  countfab: {
    position: 'absolute',
    margin: 2,
    right: 0,
    top: 50,
  },
  // levelfab: {
  //   position: 'absolute',
  //   margin: 2,
  //   left: 0,
  //   bottom: 50,
  // },
  score: {
    position: 'absolute',
    flexDirection: 'row',
    margin: 5,
    right: 0,
    top: 0,
  },
  levelfab: {
    // position: 'absolute',
    width: Math.round(windowWidth / 5),
    height: Math.round(windowWidth / 15),
    // margin: Math.round(windowWidth / 20),
    // left: 0,
    // top: 0,
    borderRadius: Math.round(windowWidth / 35),
    backgroundColor: '#afa',
    marginTop: 10,
  },

  tinyLogo: {
    width: 20,
    height: 20,
  },
  coin_number_view: {
    width: 35,
    paddingLeft: 3,
    marginTop: 0,
  },
  star_number_view: {
    width: 25,
    paddingLeft: 3,
    marginTop: 0,
  },
  startext: {
    width: 20,
  },
  coin_star_number: {
    color: 'red',
    fontSize: 15,
  },
  scoretext: {
    width: 80,
  },
  scoreboard: {
    width: 80,
    height: 20,
    marginLeft: 15,
    marginTop: 5,
  },
  logo: {
    width: 66,
    height: 58,
  },
  checkboxContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  checkbox: {
    alignSelf: 'center',
  },
  checkbox_label: {
    margin: 8,
  },
});
